export const LET = "let"
  , CONF = "configurable"
  , ENUM = "enumerable"
  , FUNC = "function"
  , OBJ = "object"
  , STR = "string"
  , NUM = "number"
  , SYM = "symbol"
  , BOOL = "boolean"
  , LEN = "length"
  , THEN = "then"
  , PROTO = "prototype"
  , NULL = null
  , VOID = undefined
